//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainWindowStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainWindowStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Resources.Localization.MainWindowStrings", typeof(MainWindowStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All documents.
        /// </summary>
        internal static string Sidebar_Buttons_AllDocuments {
            get {
                return ResourceManager.GetString("Sidebar.Buttons.AllDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        internal static string Sidebar_Buttons_Daily {
            get {
                return ResourceManager.GetString("Sidebar.Buttons.Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        internal static string Sidebar_Buttons_Favorites {
            get {
                return ResourceManager.GetString("Sidebar.Buttons.Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New document.
        /// </summary>
        internal static string Sidebar_Buttons_NewDocument {
            get {
                return ResourceManager.GetString("Sidebar.Buttons.NewDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        internal static string Sidebar_Buttons_Random {
            get {
                return ResourceManager.GetString("Sidebar.Buttons.Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recents.
        /// </summary>
        internal static string Sidebar_Buttons_Recents {
            get {
                return ResourceManager.GetString("Sidebar.Buttons.Recents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        internal static string Sidebar_Buttons_Tag {
            get {
                return ResourceManager.GetString("Sidebar.Buttons.Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash.
        /// </summary>
        internal static string Sidebar_Buttons_Trash {
            get {
                return ResourceManager.GetString("Sidebar.Buttons.Trash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate back.
        /// </summary>
        internal static string Toolbar_Buttons_Back {
            get {
                return ResourceManager.GetString("Toolbar.Buttons.Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document settings.
        /// </summary>
        internal static string Toolbar_Buttons_DocumentSettings {
            get {
                return ResourceManager.GetString("Toolbar.Buttons.DocumentSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting panel.
        /// </summary>
        internal static string Toolbar_Buttons_FormattingPanel {
            get {
                return ResourceManager.GetString("Toolbar.Buttons.FormattingPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate forward.
        /// </summary>
        internal static string Toolbar_Buttons_Forward {
            get {
                return ResourceManager.GetString("Toolbar.Buttons.Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New document.
        /// </summary>
        internal static string Toolbar_Buttons_NewDocument {
            get {
                return ResourceManager.GetString("Toolbar.Buttons.NewDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle sidebar.
        /// </summary>
        internal static string Toolbar_Buttons_ToggleSidebar {
            get {
                return ResourceManager.GetString("Toolbar.Buttons.ToggleSidebar", resourceCulture);
            }
        }
    }
}
