//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SettingsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Resources.Localization.SettingsStrings", typeof(SettingsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check orthography.
        /// </summary>
        internal static string Text_Editing_CheckOrthography_Label {
            get {
                return ResourceManager.GetString("Text.Editing.CheckOrthography.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically insert titles when pasting links.
        /// </summary>
        internal static string Text_Editing_FetchLinkTitles_Label {
            get {
                return ResourceManager.GetString("Text.Editing.FetchLinkTitles.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing.
        /// </summary>
        internal static string Text_Editing_Header {
            get {
                return ResourceManager.GetString("Text.Editing.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically insert closing brackets.
        /// </summary>
        internal static string Text_Editing_InsertClosingBrackets_Label {
            get {
                return ResourceManager.GetString("Text.Editing.InsertClosingBrackets.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string Text_Fonts_Header {
            get {
                return ResourceManager.GetString("Text.Fonts.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string Text_Fonts_System {
            get {
                return ResourceManager.GetString("Text.Fonts.System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use semibold instead of bold.
        /// </summary>
        internal static string Text_Fonts_UseSemibold_Label {
            get {
                return ResourceManager.GetString("Text.Fonts.UseSemibold.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size.
        /// </summary>
        internal static string Text_Pages_FontSize_Label {
            get {
                return ResourceManager.GetString("Text.Pages.FontSize.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to font size.
        /// </summary>
        internal static string Text_Pages_FontSize_Label_Trailing {
            get {
                return ResourceManager.GetString("Text.Pages.FontSize.Label.Trailing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        internal static string Text_Pages_Header {
            get {
                return ResourceManager.GetString("Text.Pages.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line spacing.
        /// </summary>
        internal static string Text_Pages_LineSpacing_Label {
            get {
                return ResourceManager.GetString("Text.Pages.LineSpacing.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to line spacing.
        /// </summary>
        internal static string Text_Pages_LineSpacing_Label_Trailing {
            get {
                return ResourceManager.GetString("Text.Pages.LineSpacing.Label.Trailing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compact.
        /// </summary>
        internal static string Text_Pages_LineWidth_Compact {
            get {
                return ResourceManager.GetString("Text.Pages.LineWidth.Compact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line width.
        /// </summary>
        internal static string Text_Pages_LineWidth_Label {
            get {
                return ResourceManager.GetString("Text.Pages.LineWidth.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to line width.
        /// </summary>
        internal static string Text_Pages_LineWidth_Label_Trailing {
            get {
                return ResourceManager.GetString("Text.Pages.LineWidth.Label.Trailing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacious.
        /// </summary>
        internal static string Text_Pages_LineWidth_Spacious {
            get {
                return ResourceManager.GetString("Text.Pages.LineWidth.Spacious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wide.
        /// </summary>
        internal static string Text_Pages_LineWidth_Wide {
            get {
                return ResourceManager.GetString("Text.Pages.LineWidth.Wide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size.
        /// </summary>
        internal static string Text_Spaces_FontSize_Label {
            get {
                return ResourceManager.GetString("Text.Spaces.FontSize.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to font size.
        /// </summary>
        internal static string Text_Spaces_FontSize_Label_Trailing {
            get {
                return ResourceManager.GetString("Text.Spaces.FontSize.Label.Trailing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spaces.
        /// </summary>
        internal static string Text_Spaces_Header {
            get {
                return ResourceManager.GetString("Text.Spaces.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line spacing.
        /// </summary>
        internal static string Text_Spaces_LineSpacing_Label {
            get {
                return ResourceManager.GetString("Text.Spaces.LineSpacing.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to line spacing.
        /// </summary>
        internal static string Text_Spaces_LineSpacing_Label_Trailing {
            get {
                return ResourceManager.GetString("Text.Spaces.LineSpacing.Label.Trailing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing.
        /// </summary>
        internal static string Text_Tab_Title {
            get {
                return ResourceManager.GetString("Text.Tab.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string Themes_ColorMode_Dark {
            get {
                return ResourceManager.GetString("Themes.ColorMode.Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color mode.
        /// </summary>
        internal static string Themes_ColorMode_Label {
            get {
                return ResourceManager.GetString("Themes.ColorMode.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Themes_ColorMode_Light {
            get {
                return ResourceManager.GetString("Themes.ColorMode.Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow system.
        /// </summary>
        internal static string Themes_ColorMode_System {
            get {
                return ResourceManager.GetString("Themes.ColorMode.System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separate themes for dark &amp; light modes.
        /// </summary>
        internal static string Themes_ContentThemesFollowAppThemes_Label {
            get {
                return ResourceManager.GetString("Themes.ContentThemesFollowAppThemes.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes.
        /// </summary>
        internal static string Themes_Tab_Title {
            get {
                return ResourceManager.GetString("Themes.Tab.Title", resourceCulture);
            }
        }
    }
}
